// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://52qiih4dtbbkdh5frtexq4nvou.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_cognito_identity_pool_id": "us-east-2:8ea068cc-11c1-44b7-ad28-1a04f9c5ae5d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tpxRQP7lT",
    "aws_user_pools_web_client_id": "1j5llo6c6n9sgm4jadcgvf9dq3",
    "oauth": {}
};


export default awsmobile;
